compiler-check: match-exact
resolver: nightly-2016-04-17
# compiler: ghcjs-0.2.0.820160417_ghc-7.10.3
compiler: ghc-7.10.3
system-ghc: false
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.820160417_ghc-7.10.3:
        url: "https://tolysz.org/ghcjs/nightly-2016-04-17-820160417.tar.gz"
nix:
  enable: true
packages:
- location: '.'
extra-deps:
# - network-uri-2.6.1.0
# - memory-0.12
# - unix-2.7.2.0
# - hsb2hs-0.3.1
# - Cabal-1.22.9.0
# - cabal-install-1.22.9.0
# - http-client-0.5.0
# - http-client-tls-0.3.0
# - data-default-instances-base-0.1.0.1
# - data-default-class-0.1.2.0
# - cmark-0.5.3.1
# - texmath-0.8.6.5
# resolver: lts-6.14
# resolver: nightly-2016-07-18
