compiler-check: match-exact
resolver: nightly-2016-04-17
# compiler: ghcjs-0.2.0.820160417_ghc-7.10.3
compiler: ghc-7.10.3
system-ghc: false
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.820160417_ghc-7.10.3:
        url: "https://tolysz.org/ghcjs/nightly-2016-04-17-820160417.tar.gz"
nix:
  enable: true
packages:
- location: '.'
extra-deps:
# - network-uri-2.6.1.0
