resolver: lts-7.1
# compiler: ghc-8.0.1
compiler: ghcjs-0.2.1.9007001_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007001_ghc-8.0.1:
          url: http://tolysz.org/ghcjs/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz
          sha1: e640724883238593e2d2f7f03991cb413ec0347b
system-ghc: false
nix:
  enable: false
packages:
- location: '.'
extra-deps:
- ghcjs-dom-0.3.1.0
- ghcjs-dom-jsaddle-0.3.1.0
- jsaddle-dom-0.2.0.1
- jsaddle-0.4.0.5
- ghcjs-dom-jsffi-0.3.1.0
- attoparsec-parsec-0.1.3
